### ISSUE TITLE
Javascript / nodejs checkout lifecycle documentation

### ISSUE THREAD

**Issue by phrozenra** [UltraCart/rest_api_v2_sdk_javascript#1]
Is there any documentation on the lifecycle of a javascript checkout?

I'm trying to achieve a checkout where the user doesn't have to leave the site, and while the individual API functions are documented to some extent, there's no information on what's actually required to put them all together.

**Comment by perrytew** [comment]
We have upgrade our two example checkouts to use the new API. 
They are found here:
https://github.com/UltraCart/two_page_trial
https://github.com/UltraCart/responsive_checkout

The responsive checkout has full lifecycle encoded.
