### ISSUE TITLE
There is no way to load the the package in angular 6.0

### ISSUE THREAD

**Issue by alejandrogih** [UltraCart/rest_api_v2_sdk_javascript#3]
All the time that I try to make an import in angular 6.0 like this:

`import * as UltraCartRestApiV2  from 'ultra_cart_rest_api_v2';`

I get tons of errors error like this:

> Module not found: Error: Can't resolve 'com.ultracart.admin.v2.models/CouponAmountOffSubtotalWithItemsPurchase' in '/Users/bb/Projects/Code/inteliclic/SkinTypeWeb.V2/node_modules/ultra_cart_rest_api_v2/src/com.ultracart.admin.v2.models'
> ERROR in ./node_modules/ultra_cart_rest_api_v2/src/com.ultracart.admin.v2/CouponApi.js
> Module not found: Error: Can't resolve 'com.ultracart.admin.v2.models/CouponCodesRequest' in '/Users/bb/Projects/Code/inteliclic/SkinTypeWeb.V2/node_modules/ultra_cart_rest_api_v2/src/com.ultracart.admin.v2'

[Perry removed many lines of the same type of error]

The error is bigger, but I really don't know what to do, any suggestions ?

**Comment by perrytew** [comment]
Are you using webpack?  If not, what are you using?

**Comment by perrytew** [comment]
If you're using webpack, you might need this:

```
module: {
	rules: [
		{
			parser: {
				amd: false,
			},
		},
	],
},
```

**Comment by alejandrogih** [comment]
I am just using simple ng serve, but I don´t see any webpack compiler

**Comment by alejandrogih** [comment]
any idea ?

**Comment by perrytew** [comment]
Sorry, I don't know.  We're not an angular shop.  I hate to see you stonewalled by an issue like this.  Is there any way you can put together a simple skeleton that produces this error and provide us a zip file?  If I can pull it up inside an editor and play with it, I might be able to better advise.  My apologies on the poor support.  We just haven't had the time to work with angular and our sdk.

**Comment by alejandrogih** [comment]
Yes I can create a small public project to show you the issue, we can both try to fix it. I had to continue with another solution, but it would be awesome to create a solution/integration for upcoming angular developments
