### ISSUE TITLE
CORS issue on items api endpoint

### ISSUE THREAD

**Issue by zzJoeYo** [UltraCart/rest_api_v2_sdk_javascript#5]
Hi there,

Following the code listed here: https://github.com/UltraCart/rest_api_v2_sdk_javascript/blob/master/docs/ItemApi.md#example-3

We're getting a CORS error that our domain isn't on the allow for secure.ultracart.com
```Access to XMLHttpRequest at 'https://secure.ultracart.com/rest/v2/item/items?_limit=2000&_offset=0&_placeholders=true' from origin 'https://www.our-domain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.```

We're not seeing this same CORS issue with another API endpoint that we are using for the cart that works just fine:
https://secure.ultracart.com/rest/v2/checkout/cart/5A4B56B0EBEA2A017E98526B40200B00?_expand=items

**Comment by ucjonathan** [comment]
@zzJoeYo Only the checkout REST API is available for usage in the browser via CORS.  All other REST endpoints must be used server side in NodeJS.

**Comment by zzJoeYo** [comment]
@ucjonathan - thank you for the detail - is that noted in the documentation and I missed it?

**Comment by perrytew** [comment]
No, this isn't in the documentation.  I've added a task to update the docs and provide clarity.  Thanks.
